MQ_BROKER = "localhost"
MQ_PORT = 1883
MQ_CONNECTION_KEEPALIVE = 60
SERVER_MESSAGES_TOPIC_NAME = "server-messages"
CLIENT_MESSAGES_TOPIC_NAME = "client-messages"
USER_RESPONSE_TOPIC_NAME = "user-response"
USER_REQUESTS_TOPIC_NAME = "user-requests"
